---
name: codespell

on: push  # yamllint disable-line rule:truthy

jobs:
  codespell:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: codespell-project/actions-codespell@master
