---
name: help-in-readme
on: [push]  # yamllint disable-line rule:truthy
jobs:
  help-in-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip install '.[flynt,isort]'
      - name: Verify that README contains output of darker --help
        run: darker --verify-readme
